import { DutyStatus, StopType } from "@/types/trip";

import type { TripResponse } from "@/types/trip";

/**
 * Mock TripResponse for a Richmond, VA → Philadelphia, PA → Newark, NJ trip.
 *
 * Two-day trip (~260 miles total) with all stop types represented.
 * Daily log totals each sum to 24.00 hours.
 */
export const MOCK_TRIP_RESPONSE: TripResponse = {
  id: "mock-trip-001",
  createdAt: "2026-03-16T08:00:00Z",
  route: {
    totalMiles: 260.4,
    totalDrivingHours: 5.2,
    totalTripDays: 2,
    polyline: "u}~rFnkqhMgBkC",
    segments: [
      {
        fromName: "Richmond, VA",
        toName: "Philadelphia, PA",
        miles: 170.2,
        drivingHours: 3.4,
      },
      {
        fromName: "Philadelphia, PA",
        toName: "Newark, NJ",
        miles: 90.2,
        drivingHours: 1.8,
      },
    ],
  },
  stops: [
    {
      id: 1,
      type: StopType.START,
      locationName: "Richmond, VA",
      latitude: 37.5407,
      longitude: -77.436,
      arrivalTime: "2026-03-16T08:00:00Z",
      departureTime: "2026-03-16T08:15:00Z",
      durationHours: 0.25,
      dutyStatus: DutyStatus.ON_DUTY,
      remarks: "Pre-trip inspection",
    },
    {
      id: 2,
      type: StopType.FUEL,
      locationName: "Fredericksburg, VA",
      latitude: 38.3032,
      longitude: -77.4605,
      arrivalTime: "2026-03-16T09:30:00Z",
      departureTime: "2026-03-16T10:00:00Z",
      durationHours: 0.5,
      dutyStatus: DutyStatus.ON_DUTY,
      remarks: "Fuel stop",
    },
    {
      id: 3,
      type: StopType.REST_BREAK,
      locationName: "Baltimore, MD",
      latitude: 39.2904,
      longitude: -76.6122,
      arrivalTime: "2026-03-16T11:45:00Z",
      departureTime: "2026-03-16T12:15:00Z",
      durationHours: 0.5,
      dutyStatus: DutyStatus.OFF_DUTY,
      remarks: "30-minute break",
    },
    {
      id: 4,
      type: StopType.PICKUP,
      locationName: "Philadelphia, PA",
      latitude: 39.9526,
      longitude: -75.1652,
      arrivalTime: "2026-03-16T13:30:00Z",
      departureTime: "2026-03-16T14:30:00Z",
      durationHours: 1.0,
      dutyStatus: DutyStatus.ON_DUTY,
      remarks: "Loading freight",
    },
    {
      id: 5,
      type: StopType.MANDATORY_REST,
      locationName: "Trenton, NJ",
      latitude: 40.2171,
      longitude: -74.7429,
      arrivalTime: "2026-03-16T15:30:00Z",
      departureTime: "2026-03-17T01:30:00Z",
      durationHours: 10.0,
      dutyStatus: DutyStatus.SLEEPER_BERTH,
      remarks: "10-hour mandatory rest",
    },
    {
      id: 6,
      type: StopType.DROPOFF,
      locationName: "Newark, NJ",
      latitude: 40.7357,
      longitude: -74.1724,
      arrivalTime: "2026-03-17T03:15:00Z",
      departureTime: "2026-03-17T04:15:00Z",
      durationHours: 1.0,
      dutyStatus: DutyStatus.ON_DUTY,
      remarks: "Unloading freight; post-trip inspection",
    },
  ],
  dailyLogs: [
    {
      id: "log-day-1",
      dayNumber: 1,
      date: "2026-03-16",
      totalMiles: 205.3,
      carrierName: "Swift Transport LLC",
      officeAddress: "123 Main St, Richmond, VA 23220",
      driverName: "John Smith",
      coDriver: "",
      truckNumber: "TRK-4521",
      trailerNumber: "TRL-8890",
      shippingDoc: "BOL-2026-0316",
      commodity: "General Freight",
      dutyEntries: [
        {
          startTime: "00:00",
          endTime: "08:00",
          startTimeDecimal: 0,
          endTimeDecimal: 8,
          status: DutyStatus.OFF_DUTY,
          location: "Richmond, VA",
          remarks: "",
        },
        {
          startTime: "08:00",
          endTime: "08:15",
          startTimeDecimal: 8,
          endTimeDecimal: 8.25,
          status: DutyStatus.ON_DUTY,
          location: "Richmond, VA",
          remarks: "Pre-trip inspection",
        },
        {
          startTime: "08:15",
          endTime: "09:30",
          startTimeDecimal: 8.25,
          endTimeDecimal: 9.5,
          status: DutyStatus.DRIVING,
          location: "Richmond, VA → Fredericksburg, VA",
          remarks: "",
        },
        {
          startTime: "09:30",
          endTime: "10:00",
          startTimeDecimal: 9.5,
          endTimeDecimal: 10,
          status: DutyStatus.ON_DUTY,
          location: "Fredericksburg, VA",
          remarks: "Fuel stop",
        },
        {
          startTime: "10:00",
          endTime: "11:45",
          startTimeDecimal: 10,
          endTimeDecimal: 11.75,
          status: DutyStatus.DRIVING,
          location: "Fredericksburg, VA → Baltimore, MD",
          remarks: "",
        },
        {
          startTime: "11:45",
          endTime: "12:15",
          startTimeDecimal: 11.75,
          endTimeDecimal: 12.25,
          status: DutyStatus.OFF_DUTY,
          location: "Baltimore, MD",
          remarks: "30-minute break",
        },
        {
          startTime: "12:15",
          endTime: "13:30",
          startTimeDecimal: 12.25,
          endTimeDecimal: 13.5,
          status: DutyStatus.DRIVING,
          location: "Baltimore, MD → Philadelphia, PA",
          remarks: "",
        },
        {
          startTime: "13:30",
          endTime: "14:30",
          startTimeDecimal: 13.5,
          endTimeDecimal: 14.5,
          status: DutyStatus.ON_DUTY,
          location: "Philadelphia, PA",
          remarks: "Loading freight",
        },
        {
          startTime: "14:30",
          endTime: "15:30",
          startTimeDecimal: 14.5,
          endTimeDecimal: 15.5,
          status: DutyStatus.DRIVING,
          location: "Philadelphia, PA → Trenton, NJ",
          remarks: "",
        },
        {
          startTime: "15:30",
          endTime: "24:00",
          startTimeDecimal: 15.5,
          endTimeDecimal: 24,
          status: DutyStatus.SLEEPER_BERTH,
          location: "Trenton, NJ",
          remarks: "Mandatory rest",
        },
      ],
      totals: {
        offDuty: 8.5,
        sleeperBerth: 8.5,
        driving: 4.75,
        onDuty: 2.25,
        total: 24.0,
      },
    },
    {
      id: "log-day-2",
      dayNumber: 2,
      date: "2026-03-17",
      totalMiles: 55.1,
      carrierName: "Swift Transport LLC",
      officeAddress: "123 Main St, Richmond, VA 23220",
      driverName: "John Smith",
      coDriver: "",
      truckNumber: "TRK-4521",
      trailerNumber: "TRL-8890",
      shippingDoc: "BOL-2026-0316",
      commodity: "General Freight",
      dutyEntries: [
        {
          startTime: "00:00",
          endTime: "01:30",
          startTimeDecimal: 0,
          endTimeDecimal: 1.5,
          status: DutyStatus.SLEEPER_BERTH,
          location: "Trenton, NJ",
          remarks: "Mandatory rest (continued)",
        },
        {
          startTime: "01:30",
          endTime: "01:45",
          startTimeDecimal: 1.5,
          endTimeDecimal: 1.75,
          status: DutyStatus.ON_DUTY,
          location: "Trenton, NJ",
          remarks: "Pre-trip inspection",
        },
        {
          startTime: "01:45",
          endTime: "03:15",
          startTimeDecimal: 1.75,
          endTimeDecimal: 3.25,
          status: DutyStatus.DRIVING,
          location: "Trenton, NJ → Newark, NJ",
          remarks: "",
        },
        {
          startTime: "03:15",
          endTime: "04:15",
          startTimeDecimal: 3.25,
          endTimeDecimal: 4.25,
          status: DutyStatus.ON_DUTY,
          location: "Newark, NJ",
          remarks: "Unloading freight",
        },
        {
          startTime: "04:15",
          endTime: "04:30",
          startTimeDecimal: 4.25,
          endTimeDecimal: 4.5,
          status: DutyStatus.ON_DUTY,
          location: "Newark, NJ",
          remarks: "Post-trip inspection",
        },
        {
          startTime: "04:30",
          endTime: "24:00",
          startTimeDecimal: 4.5,
          endTimeDecimal: 24,
          status: DutyStatus.OFF_DUTY,
          location: "Newark, NJ",
          remarks: "",
        },
      ],
      totals: {
        offDuty: 19.5,
        sleeperBerth: 1.5,
        driving: 1.5,
        onDuty: 1.5,
        total: 24.0,
      },
    },
  ],
};
